name: Sonarcloud Action
description: Rebuild binaries and upload to Sonarcloud
inputs:
  path-to-pom:
    description: POM file location     
    required: true
    default: ./pom.xml

branding:
  icon: "search"  
  color: "blue"

runs:
  using: "composite"
  steps:
    - run: mvn -f ${{ inputs.path-to-pom }} clean compile verify
      shell: bash